# Generated by Django 4.2.3 on 2023-07-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodCar', models.IntegerField()),
                ('NomCar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodEmp', models.IntegerField()),
                ('NomEmp', models.CharField(max_length=100)),
                ('NitEmp', models.CharField(max_length=100)),
                ('DesEmp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodPer', models.IntegerField()),
                ('NomPer', models.CharField(max_length=200)),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.cargo')),
                ('Empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresas')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='Empresas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresas'),
        ),
    ]
